#lang racket
(provide (all-defined-out))
(require "html.rkt")
(define (Math #:attr* [attr* '()] . mathml*)
  `(math ,attr* . ,mathml*))
(define (Merror #:attr* [attr* '()] . mathml*)
  `(merror ,attr* . ,mathml*))
(define (Mfrac #:attr* [attr* '()] . mathml*)
  `(mfrac ,attr* . ,mathml*))
(define (Mi #:attr* [attr* '()] . mathml*)
  `(mi ,attr* . ,mathml*))
(define (Mmultiscripts #:attr* [attr* '()] . mathml*)
  `(mmultiscripts ,attr* . ,mathml*))
(define (Mn #:attr* [attr* '()] . mathml*)
  `(mn ,attr* . ,mathml*))
(define (Mo #:attr* [attr* '()] . mathml*)
  `(mo ,attr* . ,mathml*))
(define (Mover #:attr* [attr* '()] . mathml*)
  `(mover ,attr* . ,mathml*))
(define (Mpadded #:attr* [attr* '()] . mathml*)
  `(mpadded ,attr* . ,mathml*))
(define (Mphantom #:attr* [attr* '()] . mathml*)
  `(mphantom ,attr* . ,mathml*))
(define (Mroot #:attr* [attr* '()] . mathml*)
  `(mroot ,attr* . ,mathml*))
(define (Mrow #:attr* [attr* '()] . mathml*)
  `(mrow ,attr* . ,mathml*))
(define (Ms #:attr* [attr* '()] . mathml*)
  `(ms ,attr* . ,mathml*))
(define (Mspace #:attr* [attr* '()] . mathml*)
  `(mspace ,attr* . ,mathml*))
(define (Msqrt #:attr* [attr* '()] . mathml*)
  `(msqrt ,attr* . ,mathml*))
(define (Mstyle #:attr* [attr* '()] . mathml*)
  `(mstyle ,attr* . ,mathml*))
(define (Msub #:attr* [attr* '()] . mathml*)
  `(msub ,attr* . ,mathml*))
(define (Msubsup #:attr* [attr* '()] . mathml*)
  `(msubsup ,attr* . ,mathml*))
(define (Msup #:attr* [attr* '()] . mathml*)
  `(msup ,attr* . ,mathml*))
(define (Mtable #:attr* [attr* '()] . mathml*)
  `(mtable ,attr* . ,mathml*))
(define (Mtd #:attr* [attr* '()] . mathml*)
  `(mtd ,attr* . ,mathml*))
(define (Mtext #:attr* [attr* '()] . mathml*)
  `(mtext ,attr* . ,mathml*))
(define (Mtr #:attr* [attr* '()] . mathml*)
  `(mtr ,attr* . ,mathml*))
(define (Munder #:attr* [attr* '()] . mathml*)
  `(munder ,attr* . ,mathml*))
(define (Munderover #:attr* [attr* '()] . mathml*)
  `(munderover ,attr* . ,mathml*))
(define (MB #:attr* [attr* '()] . mathml*)
  `(math ((display "block") . ,attr*) . ,mathml*))
(define ? (Mrow))
(define (: . x*)
  (cond
    ((null? x*) ?)
    ((null? (cdr x*)) (car x*))
    (else (apply Mrow x*))))
(define % Mtext)
(define ~ Mfrac)
(define _ Msub)
(define ^ Msup)
(define _^ Msubsup)
(define __ Munder)
(define ^^ Mover)
(define __^^ Munderover)
(define i.a (Mi "a"))
(define i.b (Mi "b"))
(define i.c (Mi "c"))
(define i.d (Mi "d"))
(define i.e (Mi "e"))
(define i.f (Mi "f"))
(define i.g (Mi "g"))
(define i.h (Mi "h"))
(define i.i (Mi "i"))
(define i.j (Mi "j"))
(define i.k (Mi "k"))
(define i.l (Mi "l"))
(define i.m (Mi "m"))
(define i.n (Mi "n"))
(define i.o (Mi "o"))
(define i.p (Mi "p"))
(define i.q (Mi "q"))
(define i.r (Mi "r"))
(define i.s (Mi "s"))
(define i.t (Mi "t"))
(define i.u (Mi "u"))
(define i.v (Mi "v"))
(define i.w (Mi "w"))
(define i.x (Mi "x"))
(define i.y (Mi "y"))
(define i.z (Mi "z"))
(define i.A (Mi "A"))
(define i.B (Mi "B"))
(define i.C (Mi "C"))
(define i.D (Mi "D"))
(define i.E (Mi "E"))
(define i.F (Mi "F"))
(define i.G (Mi "G"))
(define i.H (Mi "H"))
(define i.I (Mi "I"))
(define i.J (Mi "J"))
(define i.K (Mi "K"))
(define i.L (Mi "L"))
(define i.M (Mi "M"))
(define i.N (Mi "N"))
(define i.O (Mi "O"))
(define i.P (Mi "P"))
(define i.Q (Mi "Q"))
(define i.R (Mi "R"))
(define i.S (Mi "S"))
(define i.T (Mi "T"))
(define i.U (Mi "U"))
(define i.V (Mi "V"))
(define i.W (Mi "W"))
(define i.X (Mi "X"))
(define i.Y (Mi "Y"))
(define i.Z (Mi "Z"))
(define i.aa (Mi "&aopf;"))
(define i.bb (Mi "&bopf;"))
(define i.cc (Mi "&copf;"))
(define i.dd (Mi "&dopf;"))
(define i.ee (Mi "&eopf;"))
(define i.ff (Mi "&fopf;"))
(define i.gg (Mi "&gopf;"))
(define i.hh (Mi "&hopf;"))
(define i.ii (Mi "&iopf;"))
(define i.jj (Mi "&jopf;"))
(define i.kk (Mi "&kopf;"))
(define i.ll (Mi "&lopf;"))
(define i.mm (Mi "&mopf;"))
(define i.nn (Mi "&nopf;"))
(define i.oo (Mi "&oopf;"))
(define i.pp (Mi "&popf;"))
(define i.qq (Mi "&qopf;"))
(define i.rr (Mi "&ropf;"))
(define i.ss (Mi "&sopf;"))
(define i.tt (Mi "&topf;"))
(define i.uu (Mi "&uopf;"))
(define i.vv (Mi "&vopf;"))
(define i.ww (Mi "&wopf;"))
(define i.xx (Mi "&xopf;"))
(define i.yy (Mi "&yopf;"))
(define i.zz (Mi "&zopf;"))
(define i.AA (Mi "&Aopf;"))
(define i.BB (Mi "&Bopf;"))
(define i.CC (Mi "&Copf;"))
(define i.DD (Mi "&Dopf;"))
(define i.EE (Mi "&Eopf;"))
(define i.FF (Mi "&Fopf;"))
(define i.GG (Mi "&Gopf;"))
(define i.HH (Mi "&Hopf;"))
(define i.II (Mi "&Iopf;"))
(define i.JJ (Mi "&Jopf;"))
(define i.KK (Mi "&Kopf;"))
(define i.LL (Mi "&Lopf;"))
(define i.MM (Mi "&Mopf;"))
(define i.NN (Mi "&Nopf;"))
(define i.OO (Mi "&Oopf;"))
(define i.PP (Mi "&Popf;"))
(define i.QQ (Mi "&Qopf;"))
(define i.RR (Mi "&Ropf;"))
(define i.SS (Mi "&Sopf;"))
(define i.TT (Mi "&Topf;"))
(define i.UU (Mi "&Uopf;"))
(define i.VV (Mi "&Vopf;"))
(define i.WW (Mi "&Wopf;"))
(define i.XX (Mi "&Xopf;"))
(define i.YY (Mi "&Yopf;"))
(define i.ZZ (Mi "&Zopf;"))
(define i.alpha (Mi "&alpha;"))
(define i.beta (Mi "&beta;"))
(define i.gamma (Mi "&gamma;"))
(define i.delta (Mi "&delta;"))
(define i.epsilon (Mi "&epsilon;"))
(define i.zeta (Mi "&zeta;"))
(define i.eta (Mi "&eta;"))
(define i.theta (Mi "&theta;"))
(define i.iota (Mi "&iota;"))
(define i.kappa (Mi "&kappa;"))
(define i.lambda (Mi "&lambda;"))
(define i.mu (Mi "&mu;"))
(define i.nu (Mi "&nu;"))
(define i.xi (Mi "&xi;"))
(define i.omicron (Mi "&omicron;"))
(define i.pi (Mi "&pi;"))
(define i.rho (Mi "&rho;"))
(define i.sigma (Mi "&sigma;"))
(define i.tau (Mi "&tau;"))
(define i.upsilon (Mi "&upsilon;"))
(define i.phi (Mi "&phi;"))
(define i.chi (Mi "&chi;"))
(define i.psi (Mi "&psi;"))
(define i.omega (Mi "&omega;"))
(define i.Alpha (Mi "&Alpha;"))
(define i.Beta (Mi "&Beta;"))
(define i.Gamma (Mi "&Gamma;"))
(define i.Delta (Mi "&Delta;"))
(define i.Epsilon (Mi "&Epsilon;"))
(define i.Zeta (Mi "&Zeta;"))
(define i.Eta (Mi "&Eta;"))
(define i.Theta (Mi "&Theta;"))
(define i.Iota (Mi "&Iota;"))
(define i.Kappa (Mi "&Kappa;"))
(define i.Lambda (Mi "&Lambda;"))
(define i.Mu (Mi "&Mu;"))
(define i.Nu (Mi "&Nu;"))
(define i.Xi (Mi "&Xi;"))
(define i.Omicron (Mi "&Omicron;"))
(define i.Pi (Mi "&Pi;"))
(define i.Rho (Mi "&Rho;"))
(define i.Sigma (Mi "&Sigma;"))
(define i.Tau (Mi "&Tau;"))
(define i.Upsilon (Mi "&Upsilon;"))
(define i.Phi (Mi "&Phi;"))
(define i.Chi (Mi "&Chi;"))
(define i.Psi (Mi "&Psi;"))
(define i.Omega (Mi "&Omega;"))
(define n.0 (Mn "0"))
(define n.1 (Mn "1"))
(define n.2 (Mn "2"))
(define n.3 (Mn "3"))
(define n.4 (Mn "4"))
(define n.5 (Mn "5"))
(define n.6 (Mn "6"))
(define n.7 (Mn "7"))
(define n.8 (Mn "8"))
(define n.9 (Mn "9"))
(define o.comma (Mo ","))
(define o.cm o.comma)
(define o.it (Mo "&it;"))
(define o.i* o.it)
(define o.af (Mo "&af;"))
(define o.plus (Mo "&plus;"))
(define o.+ o.plus)
(define o.minus (Mo "&minus;"))
(define o.- o.minus)
(define o.times (Mo "&times;"))
(define o.c* o.times)
(define o.divide (Mo "&divide;"))
(define o.equals (Mo "&equals;"))
(define o.= o.equals)
(define o.ne (Mo "&ne;"))
(define o.plusmn (Mo "&plusmn;"))
(define o.+- o.plusmn)
(define o.not (Mo "&not;"))
(define o.lt (Mo "&lt;"))
(define o.< o.lt)
(define o.gt (Mo "&gt;"))
(define o.> o.gt)
(define o.deg (Mo "&deg;"))
(define o.percnt (Mo "&percnt;"))
(define o.% o.percnt)
(define o.forall (Mo "&forall;"))
(define o.comp (Mo "&comp;"))
(define o.part (Mo "&part;"))
(define o.exist (Mo "&exist;"))
(define i.empty (Mi "&empty;"))
(define o.nabla (Mo "&nabla;"))
(define o.in (Mo "&in;"))
(define o.isin (Mo "&isin;"))
(define o.notin (Mo "&notin;"))
(define o.ni (Mo "&ni;"))
(define o.notni (Mo "&notni;"))
(define o.prod (Mo "&prod;"))
(define o.coprod (Mo "&coprod;"))
(define o.sum (Mo "&sum;"))
(define o.mnplus (Mo "&mnplus;"))
(define o.-+ o.mnplus)
(define o.setminus (Mo "&setminus;"))
(define o.\\ o.setminus)
(define o.lowast (Mo "&lowast;"))
(define o.* o.lowast)
(define o.compfn (Mo "&compfn;"))
(define o.prop (Mo "&prop;"))
(define i.infin (Mi "&infin;"))
(define o.ang (Mo "&ang;"))
(define o.mid (Mo "&mid;"))
(define o.nmid (Mo "&nmid;"))
(define o.parallel (Mo "&parallel;"))
(define o.npar (Mo "&npar;"))
(define o.and (Mo "&and;"))
(define o.or (Mo "&or;"))
(define o.cap (Mo "&cap;"))
(define o.cup (Mo "&cup;"))
(define o.int (Mo "&int;"))
(define o.Int (Mo "&Int;"))
(define o.iiint (Mo "&iiint;"))
(define o.conint (Mo "&conint;"))
(define o.Conint (Mo "&Conint;"))
(define o.Cconint (Mo "&Cconint;"))
(define o.cwint (Mo "&cwint;"))
(define o.cwconint (Mo "&cwconint;"))
(define o.awconint (Mo "&awconint;"))
(define o.there4 (Mo "&there4;"))
(define o.because (Mo "&because;"))
(define o.ratio (Mo "&ratio;"))
(define o.Colon (Mo "&Colon;"))
(define o.sim (Mo "&sim;"))
(define o.bsim (Mo "&bsim;"))
(define o.asymp (Mo "&asymp;"))
(define o.asympeq (Mo "&asympeq;"))
(define o.colone (Mo "&colone;"))
(define o.:= o.colone)
(define o.equiv (Mo "&equiv;"))
(define o.le (Mo "&le;"))
(define o.<= o.le)
(define o.ge (Mo "&ge;"))
(define o.>= o.ge)
(define o.sub (Mo "&sub;"))
(define o.sup (Mo "&sup;"))
(define o.nsub (Mo "&nsub;"))
(define o.nsup (Mo "&nsup;"))
(define o.sube (Mo "&sube;"))
(define o.supe (Mo "&supe;"))
(define o.nsube (Mo "&nsube;"))
(define o.nsupe (Mo "&nsupe;"))
(define o.sqsub (Mo "&sqsub;"))
(define o.sqsup (Mo "&sqsup;"))
(define o.sqsube (Mo "&sqsube;"))
(define o.sqsupe (Mo "&sqsupe;"))
(define o.sqcap (Mo "&sqcap;"))
(define o.sqcup (Mo "&sqcup;"))
(define o.oplus (Mo "&oplus;"))
(define o.otimes (Mo "&otimes;"))
(define o.o* o.otimes)
(define o.vdash (Mo "&vdash;"))
(define o.\|- o.vdash)
(define o.dashv (Mo "&dashv;"))
(define o.top (Mo "&top;"))
(define i.top (Mi "&top;"))
(define o.perp (Mo "&perp;"))
(define i.perp (Mi "&perp;"))
(define o.vDash (Mo "&vDash;"))
(define o.\|= o.vDash)
(define o.vltri (Mo "&vltri;"))
(define o.vrtri (Mo "&vrtri;"))
(define o.xwedge (Mo "&xwedge;"))
(define o.xvee (Mo "&xvee;"))
(define o.xcap (Mo "&xcap;"))
(define o.xcup (Mo "&xcup;"))
(define o.diamond (Mo "&diamond;"))
(define o.sdot (Mo "&sdot;"))
(define o.d* o.sdot)
(define o.vellip (Mo "&vellip;"))
(define o..v o.vellip)
(define o.ctdot (Mo "&ctdot;"))
(define o..h o.ctdot)
(define o.utdot (Mo "&utdot;"))
(define o..u o.utdot)
(define o.dtdot (Mo "&dtdot;"))
(define o..d o.dtdot)
(define o.larr (Mo "&larr;"))
(define o.<- o.larr)
(define o.uarr (Mo "&uarr;"))
(define o.rarr (Mo "&rarr;"))
(define o.-> o.rarr)
(define o.darr (Mo "&darr;"))
(define o.harr (Mo "&harr;"))
(define o.<-> o.harr)
(define o.varr (Mo "&varr;"))
(define o.mapsto (Mo "&mapsto;"))
(define o.\|-> o.mapsto)
(define o.lArr (Mo "&lArr;"))
(define o.uArr (Mo "&uArr;"))
(define o.rArr (Mo "&rArr;"))
(define o.dArr (Mo "&dArr;"))
(define o.=> o.rArr)
(define o.hArr (Mo "&hArr;"))
(define o.<=> o.hArr)
(define o.prime (Mo "&prime;"))
(define o.! (Mo "!"))
(define o.fact o.!)
(define o.OverBar (Mo "&OverBar;"))
(define o./
  (Mo "/" #:attr* '((lspace "0") (rspace "0"))))
(define ((make-op op n u) . x*)
  (cond
    ((null? x*) (n))
    ((null? (cdr x*)) (u (car x*)))
    (else
     (let iter ((x (car x*)) (x* (cdr x*)) (r '()))
       (if (null? x*)
           (apply Mrow (reverse (cons x r)))
           (iter (car x*)
                 (cdr x*)
                 (cons op (cons x r))))))))
(define (err0 id)
  (lambda () (error id "")))
(define (err1 id)
  (lambda (x) (error id "~s" x)))
(define (make-infix0 op id)
  (make-op op
    (err0 id)
    (err1 id)))
(define (make-infix1 op id)
  (make-op op
    (err0 id)
    (lambda (x) (Mrow op x))))
(define ((make-infix2 op) x y)
  (Mrow x op y))
(define ((make-prefix op) x)
  (Mrow op x))
(define ((make-suffix op) x)
  (Mrow x op))
(define ((make-bigop0 op) u o e)
  (Mrow (Munderover op u o) e))
(define ((make-bigop1 op) u o e)
  (Mrow (Msubsup op u o) e))
(define-syntax define-infix0*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-infix0 op 'id))
       ...))))
(define-syntax define-infix1*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-infix1 op 'id))
       ...))))
(define-syntax define-infix2*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-infix2 op))
       ...))))
(define-syntax define-prefix*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-prefix op))
       ...))))
(define-syntax define-suffix*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-suffix op))
       ...))))
(define-syntax define-bigop0*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-bigop0 op))
       ...))))
(define-syntax define-bigop1*
  (syntax-rules ()
    ((_ (id op) ...)
     (begin
       (define id (make-bigop1 op))
       ...))))
(define-infix0*
  (&it o.it)
  (&i* o.i*)
  (&times o.times)
  (&c* o.c*)
  (&equals o.equals)
  (&= o.=)
  (&lt o.lt)
  (&< o.<)
  (&gt o.gt)
  (&> o.>)
  (&in o.in)
  (&isin o.isin)
  (&ni o.ni)
  (&compfn o.compfn)
  (&and o.and)
  (&or o.or)
  (&cap o.cap)
  (&cup o.cup)
  (&colone o.colone)
  (&:= o.:=)
  (&equiv o.equiv)
  (&le o.le)
  (&<= o.<=)
  (&ge o.ge)
  (&>= o.>=)
  (&sub o.sub)
  (&sup o.sup)
  (&sube o.sube)
  (&supe o.supe)
  (&sqsub o.sqsub)
  (&sqsup o.sqsup)
  (&sqsube o.sqsube)
  (&sqsupe o.sqsupe)
  (&sqcap o.sqcap)
  (&sqcup o.sqcup)
  (&oplus o.oplus)
  (&otimes o.otimes)
  (&o* o.otimes)
  (&vltri o.vltri)
  (&vrtri o.vrtri)
  (&sdot o.sdot)
  (&d* o.d*)
  (&larr o.larr)
  (&<- o.<-)
  (&uarr o.uarr)
  (&rarr o.rarr)
  (&-> o.->)
  (&darr o.darr)
  (&harr o.harr)
  (&<-> o.<->)
  (&lArr o.lArr)
  (&uArr o.uArr)
  (&rArr o.rArr)
  (&=> o.=>)
  (&dArr o.dArr)
  (&hArr o.hArr)
  (&<=> o.<=>))
(define-infix1*
  (&plus o.plus)
  (&+ o.+)
  (&minus o.minus)
  (&- o.-)
  (&plusmn o.plusmn)
  (&+- o.+-)
  (&mnplus o.mnplus)
  (&-+ o.-+))
(define-infix2*
  (&af o.af)
  (&divide o.divide)
  (&notin o.notin)
  (&notni o.notni)
  (&setminus o.setminus)
  (&\\ o.\\)
  (&mid o.mid)
  (&nmid o.nmid)
  (&parallel o.parallel)
  (&npar o.npar)
  (&ratio o.ratio)
  (&sim o.sim)
  (&bsim o.bsim)
  (&asymp o.asymp)
  (&vdash o.vdash)
  (&\|- o.\|-)
  (&vDash o.vDash)
  (&\|= o.\|=)
  (&mapsto o.mapsto)
  (&\|-> o.\|->)
  (&/ o./))
(define-prefix*
  (&not o.not)
  (&part o.part)
  (&nabla o.nabla))
(define-suffix*
  (&percnt o.percnt)
  (&% o.%)
  (&! o.!)
  (&fact o.fact))
(define-bigop0*
  (&prod o.prod)
  (&coprod o.coprod)
  (&sum o.sum)
  (&xwedge o.xwedge)
  (&xvee o.xvee)
  (&xcap o.xcap)
  (&xcup o.xcup))
(define-bigop1*
  (&int o.int)
  (&Int o.Int)
  (&iiint o.iiint)
  (&conint o.conint)
  (&Conint o.Conint)
  (&Cconint o.Cconint)
  (&cwint o.cwint)
  (&cwconint o.cwconint)
  (&awconint o.awconint))
(define &comma
  (make-op o.comma
    (lambda () ?)
    (lambda (x) x)))
(define &cm &comma)
(define (&comma1 x)
  (Mrow o.comma x))
(define &cm1 &comma1)
(define &lowast
  (make-op o.lowast
    (lambda () (err0 '&lowast))
    (lambda (x) (Msup x o.lowast))))
(define &* &lowast)
(define (&prime x)
  (Msup x o.prime))
(define &^ &prime)
(define (&OverBar x)
  (Mover x o.OverBar))
(define n.-1 (&- n.1))
(define n.-2 (&- n.2))
(define n.-3 (&- n.3))
(define n.-4 (&- n.4))
(define n.-5 (&- n.5))
(define n.-6 (&- n.6))
(define n.-7 (&- n.7))
(define n.-8 (&- n.8))
(define n.-9 (&- n.9))
(define (&inv x)
  (Msup x n.-1))
(define o.lparen (Mo "("))
(define o.rparen (Mo ")"))
(define o.lbrack (Mo "["))
(define o.rbrack (Mo "]"))
(define o.lcurly (Mo "{"))
(define o.rcurly (Mo "}"))
(define o.lverti (Mo "|"))
(define o.rverti (Mo "|"))
(define o.langle (Mo "&lang;"))
(define o.rangle (Mo "&rang;"))
(define o.lVerti (Mo "&Vert;"))
(define o.rVerti (Mo "&Vert;"))
(define o.lpare0
  (Mo "(" #:attr* '((stretchy "false"))))
(define o.rpare0
  (Mo ")" #:attr* '((stretchy "false"))))
(define o.lbrac0
  (Mo "[" #:attr* '((stretchy "false"))))
(define o.rbrac0
  (Mo "]" #:attr* '((stretchy "false"))))
(define o.lcurl0
  (Mo "{" #:attr* '((stretchy "false"))))
(define o.rcurl0
  (Mo "}" #:attr* '((stretchy "false"))))
(define o.lvert0
  (Mo "|" #:attr* '((stretchy "false"))))
(define o.rvert0
  (Mo "|" #:attr* '((stretchy "false"))))
(define o.langl0
  (Mo "&lang;" #:attr* '((stretchy "false"))))
(define o.rangl0
  (Mo "&rang;" #:attr* '((stretchy "false"))))
(define o.lVert0
  (Mo "&Vert;" #:attr* '((stretchy "false"))))
(define o.rVert0
  (Mo "&Vert;" #:attr* '((stretchy "false"))))
(define ((make-bracket l r) . x*)
  (Mrow l (apply : x*) r))
(define-syntax define-bracket*
  (syntax-rules ()
    ((_ (id l r) ...)
     (begin
       (define id (make-bracket l r))
       ...))))
(define-bracket*
  (paren o.lparen o.rparen)
  (pare0 o.lpare0 o.rpare0)
  (brack o.lbrack o.rbrack)
  (brac0 o.lbrac0 o.rbrac0)
  (curly o.lcurly o.rcurly)
  (curl0 o.lcurl0 o.rcurl0)
  (verti o.lverti o.rverti)
  (vert0 o.lvert0 o.rvert0)
  (angle o.langle o.rangle)
  (angl0 o.langl0 o.rangl0)
  (Verti o.lVerti o.rVerti)
  (Vert0 o.lVert0 o.rVert0))
(define @ pare0)
(define (tuple . x*)
  (paren (apply &cm x*)))
(define (tupl0 . x*)
  (pare0 (apply &cm x*)))
(define (&list . x*)
  (brack (apply &cm x*)))
(define (&lis0 . x*)
  (brac0 (apply &cm x*)))
(define (&abs x) (vert0 x))
(define (&norm x) (Vert0 x))
(define (ap f . x*)
  (&af f (apply tupl0 x*)))
(define (app f . x*)
  (&af f (apply brac0 x*)))
(define (tag? l x)
  (and (pair? l)
       (eq? (car l) x)))
(define (&mtable #:attr* [attr* '()] . row*)
  (define (R r)
    (if (tag? r 'mtr)
        (apply
         (lambda (tag attr* . d*)
           `(mtr ,attr* . ,(map D d*)))
         r)
        (apply Mtr (map D r))))
  (define (D d)
    (if (tag? d 'mtd) d (Mtd d)))
  `(mtable ,attr* . ,(map R row*)))
(define-syntax &Mtable
  (syntax-rules ()
    ((_ #:attr* attr* (x ...) ...)
     (&mtable #:attr* attr* (list x ...) ...))
    ((_ (x ...) ...)
     (&mtable (list x ...) ...))))
(define (&matrix #:attr* [attr* '()] . row*)
  (brack
   (keyword-apply
    &mtable '(#:attr*) (list attr*) row*)))
(define-syntax &Matrix
  (syntax-rules ()
    ((_ #:attr* attr* (x ...) ...)
     (&matrix #:attr* attr* (list x ...) ...))
    ((_ (x ...) ...)
     (&matrix (list x ...) ...))))
(define (&matrix0 #:attr* [attr* '()] . row*)
  (paren
   (keyword-apply
    &mtable '(#:attr*) (list attr*) row*)))
(define-syntax &Matrix0
  (syntax-rules ()
    ((_ #:attr* attr* (x ...) ...)
     (&matrix0 #:attr* attr* (list x ...) ...))
    ((_ (x ...) ...)
     (&matrix0 (list x ...) ...))))
(define (&det #:attr* [attr* '()] . row*)
  (Verti
   (keyword-apply
    &mtable '(#:attr*) (list attr*) row*)))
(define-syntax &Det
  (syntax-rules ()
    ((_ #:attr* attr* (x ...) ...)
     (&det #:attr* attr* (list x ...) ...))
    ((_ (x ...) ...)
     (&det (list x ...) ...))))
(define (&choice #:attr* [attr* '()] . row*)
  (Mrow
   o.lcurly
   (keyword-apply
    &mtable '(#:attr*) (list attr*) row*)))
(define-syntax &Choice
  (syntax-rules ()
    ((_ #:attr* attr* (x ...) ...)
     (&choice #:attr* attr* (list x ...) ...))
    ((_ (x ...) ...)
     (&choice (list x ...) ...))))
(define (&choice0 #:attr* [attr* '()] . row*)
  (Mrow
   o.lcurly
   (keyword-apply
    &mtable '(#:attr*) (list attr*)
    (map (lambda (row)
           (list (car row)
                 (Mtd #:attr* '((columnalign "left"))
                      (&cm1 (cadr row)))))
         row*))))
(define-syntax &Choice0
  (syntax-rules ()
    ((_ #:attr* attr* (x ...) ...)
     (&choice0 #:attr* attr* (list x ...) ...))
    ((_ (x ...) ...)
     (&choice0 (list x ...) ...))))
(define ((definition #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "definition")))
   (B (format "定义~a." n)) " " x*))
(define ((lemma #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "lemma")))
   (B (format "引理~a." n)) " " x*))
(define ((theorem #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "theorem")))
   (B (format "定理~a." n)) " " x*))
(define ((corollary #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "corollary")))
   (B (format "推论~a." n)) " " x*))
(define ((example #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "example")))
   (B (format "例子~a." n)) " " x*))
(define ((notation #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "notation")))
   (B (format "记号~a." n)) " " x*))
(define ((comment #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "comment")))
   (B (format "注记~a." n)) " " x*))
(define ((program #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "program")))
   (B (format "程序~a." n)) " " x*))
(define ((exercise #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "exercise")))
   (B (format "练习~a." n)) " " x*))
(define Q.E.D.
  (Div (B "Q.E.D." ) #:attr* '((style "text-align: right;"))))
(define ((proof #:n [n ""]) . x*)
  (keyword-apply
   Div '(#:attr*) '(((class "proof")))
   (B (format "证明~a." n)) " " `(,@x* ,Q.E.D.)))
